steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hopeful-object-378409/rental-fe', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/hopeful-object-378409/rental-fe']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'rental-fe', '--image', 'gcr.io/hopeful-object-378409/rental-fe', '--region', 'asia-southeast2']
images:
- gcr.io/hopeful-object-378409/rental-fe